### ISSUE TITLE
Error Message: The specified object was not found in the store

### ISSUE THREAD

**Issue by farao780** [RogerSelwyn/O365-HomeAssistant#29] opened 2022-03-21 08:48 UTC
After updating to last version (2.4.0) my inbox sensor became unavailable
last error line says:

 File "/usr/local/lib/python3.9/site-packages/O365/connection.py", line 762, in _internal_request
    raise HTTPError('{} | Error Message: {}'.format(e.args[0], error_message), response=response) from None
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://graph.microsoft.com/v1.0/me/calendars/xxxxxxxxxxxxxxxxxxxxxxxxx= | Error Message: The specified object was not found in the store.

re-checked permission for my Azure app , everything is there.
what should I review?

**Comment by RogerSelwyn** [comment] 2022-03-21 09:06
Please downgrade to the last version that worked for you and confirm that it works, so we can isolate that it is the upgrade that caused the problem.

**Comment by RogerSelwyn** [comment] 2022-03-21 09:07
Also what version were you using, when it worked?

**Comment by RogerSelwyn** [comment] 2022-03-21 09:09
> File "/usr/local/lib/python3.9/site-packages/O365/connection.py", line 762, in _internal_request raise HTTPError('{} | Error Message: {}'.format(e.args[0], error_message), response=response) from None requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://graph.microsoft.com/v1.0/me/calendars/xxxxxxxxxxxxxxxxxxxxxxxxx= | Error Message: The specified object was not found in the store.

Finally, this error suggests a calendar isn't there, not you inbox. Have you deleted a calendar that you have defined in o365_calendars.yaml

**Comment by RogerSelwyn** [comment] 2022-03-21 09:33
Can you provide a copy of your config (obfuscating as needed). Both config.yaml and o365_calendars.yaml?

You can downgrade via HACS by the way, just select re-install and it will provide versions to download :-)

**Comment by farao780** [comment] 2022-03-23 05:05
in config.yaml there is only the include file. so I have :
 
 config/components/o365.yaml :
 
  client_secret: "xxx"
  client_id: "xxx"
  alt_auth_flow: true
  email_sensor:
    - name: inbox
      max_items: 2
      is_unread: True

and /config/o365_calendars.yaml :

- cal_id: xxx
  entities:
  - device_id: xxx
    end_offset: 24
    name: xxx
    start_offset: 0
    track: true

- cal_id: xxx
  entities:
  - device_id: Untitled
    end_offset: 24
    name: Untitled
    start_offset: 0
    track: true

- cal_id: xxx
  entities:
  - device_id: Calendar
    end_offset: 24
    name: Calendar
    start_offset: 0
    track: true

- cal_id: xxx
  entities:
  - device_id: "Zile de na\u0219tere"
    end_offset: 24
    name: "Zile de na\u0219tere"
    start_offset: 0
    track: true

- cal_id: xxx
  entities:
  - device_id: "S\u0103rb\u0103tori \xEEn Rom\xE2nia"
    end_offset: 24
    name: "S\u0103rb\u0103tori \xEEn Rom\xE2nia"
    start_offset: 0
    track: true

**Comment by RogerSelwyn** [comment] 2022-03-23 08:18
I can't immediately see anything wrong with it, but it is always good to post in a code block using the <> in the Guthub formatting bar.

And in theory there should be nothing wrong with it because it works in 2.3.1. So if you would like to debug it, are you prepared to try version 3.x, and I can add some extra debug code to try and figure out the issue?

**Comment by RogerSelwyn** [comment] 2022-03-23 08:21
Also if there is more of the error, please post all of it.

**Comment by RogerSelwyn** [comment] 2022-03-23 08:26
And hopefully finally `device_id: "Zile de na\u0219tere"` is this a calendar in a subfolder, or it is another users calendar?

**Comment by farao780** [comment] 2022-03-23 09:02
1. No problem to test another version.
2. Due to restarting I don't have error messages in log.
3. All are my calendars, but for now I cannot remember if birth days are in 0365 or are imported via sync from gmail

**Comment by RogerSelwyn** [comment] 2022-03-23 09:05
Thanks. I'm just doing some work on shared items, then I'll post a new version.

**Comment by RogerSelwyn** [comment] 2022-03-23 09:45
I've added a new version with some extra debugging around calendars - https://github.com/RogerSelwyn/O365-HomeAssistant/releases/tag/v3.0.0a5

In case you don't find it in HACS, select the three dots menu on the O365 integration, then select to redownload, then select 'Show beta versions'. After a moment it should show the beta versions. To go back to v2.3.1, you will probably need to untick the show beta box.

**Comment by RogerSelwyn** [comment] 2022-03-23 09:47
You will also need to enable debug logging for the integration.

```
logger:
  default: warning
  logs:
    custom_components.o365: debug
```

**Comment by The-Darjeeling** [comment] 2022-03-26 14:30
Ran into this error too, downgrading to v2.3.1 and going onto beta v3.0.0a5 didnt resolve however i went and compared the cal_id in the error log and found it name was a duplicate of a calendar already on there. detleting the duplicates got everything working again. 

When i moved onto v2.4.0 i'd cleared out calendars i didn't want & added a bunch of searches. I must have botched the yamml and left the duplicated Id's. 

v3.0.0a5 works fine regardless

**Comment by RogerSelwyn** [comment] 2022-03-26 14:47
Two strange things with that:

- Firstly that it allowed duplicates

- Secondly that any duplicate entry caused an error (though  to be honest I've never tried a duplicate). I'd expect that it would still work. My suspicion would be that an incorrect value has been aded somehow.

I'll try using an old calendar.yaml, against the latest v3 and see if that generates wrong duplicates

**Comment by RogerSelwyn** [comment] 2022-03-26 16:00
I've just checked against point 2. If I create a duplicate entry in o365_calendars.yaml with a modified device_id and name (because otherwise it makes no sense), then it just gives a duplicate calendar entry with the appropriate name/entity_id. If I don't change the device_id, then it creates only one calendar.

@The-Darjeeling I suspect that whilst the entries looked the same, they weren't really (they vary by only a few chars).

It would be good to know if the yaml file got modified as part of the upgrade, and whether somehow incorrect values were added. Or whether the values were there before upgrade, and were somehow being suppressed. It would be great if you could take a look at an old backup if you have one.

**Comment by The-Darjeeling** [comment] 2022-03-27 15:56
Thanks for trying to replicate. Oldest back up was 5 days ago unfortunatly, the upgrade was done on the 08/03/22. 

It was a duplicate in the sense of the calendar name, the Cal_ID was different and seemingly non existant on graph which threw up the error. i'm wondering if did something when adding some search catagories, either that or the ID's changed at a tennant level. 

I'm betryaing my lack of coding knowledge here but, would there be a way to allow the rest of the intergation to run in the event of a fault? then even where theres something wrong with a specfifc caldendar or inbox the rest would work.

**Comment by RogerSelwyn** [comment] 2022-03-27 16:14
That's what I've done in the latest alpha release, it will display an error (which I can't suppress and is the roe that shows the calendar_id) plus a warning which I am generating with the calendar name and device_id to help with identification. You can test this by adding an entry to calendars.yaml with an incorrect calendar_id. If you see the error bu don't see the warning then you just need to enable warning level logging for custom_ components.o365 in config.yaml.

**Comment by RogerSelwyn** [comment] 2022-04-11 13:11
No further information provided so closing. Please reopen if needed.

**Closed by RogerSelwyn** 2022-04-11 13:11 UTC
Labels: help wanted
